FORMAT: 1A
HOST: https://v1.messagebus.dudesolutions.io

USECOMMONSDKLIBRARY: TRUE
GENERATEASYNCCODE: TRUE
GENERATEINTERFACES: TRUE
USEMETHODPREFIX: TRUE
USEMODELPOSTFIX: FALSE
USECONTROLLERPOSTFIX: FALSE
USEENUMPOSTFIX: FALSE
USECONSTRUCTORSFORCONFIG: TRUE
CSHARPDEFAULTNAMESPACE: DSI.SDK.MessageBus
JAVADEFAULTNAMESPACE: io.dudesolutions.messagebus
BRANDLABEL: Dude Solutions, Inc.
USERAGENT: Dude SDK
NULLIFY404: TRUE
VALIDATEREQUIREDPARAMETERS: FALSE
COLLECTPARAMETERS: TRUE
ARRAYSERIALIZATION: Plain

# Dude MessageBus Api

## Reference
Good reference document: https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/Polls%20API.md

## Authentication
*MessageBus Api* uses OAuth v2 Authentication. First you create a new (or acquire existing) OAuth v2 token using [DudeAuth](https://www.dudeauth.com/).

New to *OAuth*?  Check out the [OAuth Bible](http://oauthbible.com/) for good reference material.

MessageBus API also allows a bearer token to be passed in the query string. (i.e. /somepath?accessToken=*token*)

## Media Types
Where applicable this API uses the *JSON* media-type to represent resources.

Requests and responses with a message-body use plain JSON to set or update resources.

## Error States
Common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used throughout this API.

In addition to standard response codes the response object returned from the server during an exception event may contain additional information in the following JSON format:

        {
            "message": "SOME MESSAGE",
            "dudeReferenceId": "3523845A-4729-4CCB-9E16-01DEADF6C2DF",
            "stackTrace": "Null, Typically"
        }

## Data Restriction
Depending on the access level granted to the calling client certain data elements throughout this API will be removed and not returned.

## Known Issues
None at this time

# Group System Information
Check API System Information.

## S.I. Check [/]
Retrieve api version, vitals, links, etc.

### GET

+ Response 200 (application/json)
    + Attributes (System Information)

# Group Heartbeat
Check health of dependent services.

## Heartbeat Check [/heartbeat]
The heartbeat is exposed and provided to check for availability of the service.
Any response that does not provide a ```200 OK``` response code should be treated as an error.

### GET

+ Response 200 (application/json)
    + Headers

            X-Dude-Api-Limit: Unlimited or Number
            X-Dude-Api-Remaining: Unlimited or Number
            X-Dude-Api-Server: Api Server ID

    + Attributes (Heartbeat)

# Group Messages
Add messages to the message bus

## Change Message [/messages]
This endpoint allows for the post of change messages.

### POST

+ Request
    + Attributes (Message Request Object)

+ Response 202 (application/json; charset=utf-8)
    + Attributes (Message Response Object)

# Data Structures

## System Information (object)
Represents the MessageBus Api application name, version, etc. Returned in the heartbeat

###Properties
+ `application`: `Dude MessageBus Api` (string, required) - The name of the application.
+ `version` : `1.0.0.0` (string, required) - The assembly version.
+ `apiVersion` : `1.0.0.0` (string, required) - The API version.
+ `vitals` (Heartbeat, required) - The state of the system dependencies.
+ `links` (array[System Links], required) - The API routes.


## System Links (object)
Array of links returned in the System Information

###Properties
+ `endpoint` : `MessageBus` (string, required) - The name of the endpoint.
+ `action` : `Get` (string, required) - The REST action.
+ `route` : `/accounts/{accountId}/changes` (string, required) - The route to the endpoint.

## Heartbeat (object)
Represents the data returned by the heartbeat request

###Properties
+ `cachevitalcheck`: true (boolean, required) - Vital check to ensure cache is available and online

## Message Request Object (object)
Represents the message data for a message request to be pushed onto the message bus

###Properties
+ `topic`: `change-event` (string, required) - The topic of the message
+ `body` (object, required) - The message being pushed onto Kafka

## Message Response Object (object)
Represents the message data for a change message request to be pushed onto the message bus

###Properties
+ `partition`: 1 (number, required) - The partition of the message being inserted onto Kafka
+ `offset`: 10 (number, required) - The partition of the message being insert onto Kafka
